/**
 * 日報自動作成・Slack通知スクリプト
 * 
 * 設定手順:
 * 1. GASエディタの歯車マーク(プロジェクト設定) > スクリプトプロパティ に以下を追加
 *    - GEMINI_API_KEY: GeminiのAPIキー (既存のものがあればそのまま)
 *    - SLACK_WEBHOOK_URL: SlackのIncoming Webhook URL
 *    - TARGET_CALENDAR_ID: 対象のGoogleカレンダーID（デフォルトを読み込む場合は設定不要。特定のカレンダーを読みたい場合のみ設定）
 * 2. `setupDailyTrigger` 関数（このファイルの下部）を1回だけ手動実行して、毎日のトリガーを設定する
 */

const DAILY_CONFIG = {
  get GEMINI_API_KEY() { return PropertiesService.getScriptProperties().getProperty('GEMINI_API_KEY') || ''; },
  get SLACK_WEBHOOK_URL() { return PropertiesService.getScriptProperties().getProperty('SLACK_WEBHOOK_URL') || ''; },
  get TARGET_CALENDAR_ID() { return PropertiesService.getScriptProperties().getProperty('TARGET_CALENDAR_ID') || 'primary'; },
  
  // 記録をチェックするシート名（既存の「DailySummary」を使用）
  DAILY_SUMMARY_SHEET: 'DailySummary',
  
  // 自動チェック・実行する時間（何時台に起動するか。18〜19時の間に実行されます）
  TRIGGER_HOUR: 18
};

/**
 * 【メイン関数】日報の未提出チェックと自動作成・Slack通知処理
 */
function checkAndGenerateDailyReport() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  let dailySheet = ss.getSheetByName(DAILY_CONFIG.DAILY_SUMMARY_SHEET);
  
  const today = new Date();
  
  // 1. 本日のAI時間計測・日報記録があるかチェック
  const hasRecord = checkTodayRecord(dailySheet, today);
  
  if (hasRecord) {
    Logger.log('本日の計測・日報は既に記録されています。何もしません。');
    return;
  }
  
  // ---- 記録がなかった場合の処理 ----
  
  Logger.log('本日の記録がありません。自動生成とSlack通知を開始します。');
  
  // 2. Slackに未提出の「アラート」を送信
  sendSlackMessage("🚨 *【未提出アラート】*\n本日の「AI時間計測・日報」がまだ記録されていません。\nカレンダーの予定データから、AI(Gemini)を用いて日報を自動生成します...");
  
  // 3. 今日のカレンダー予定を取得
  const eventsInfo = getTodayCalendarEvents(today);
  
  if (eventsInfo.eventCount === 0) {
    sendSlackMessage("本日のカレンダー予定が見つからなかったため、日報の自動生成をスキップしました。手動でご提出をお願いします。");
    return;
  }
  
  // 4. Gemini APIで日報を自動生成
  const reportText = generateReportWithGemini(eventsInfo, today);
  
  // 5. Slackに自動生成した日報をアップロード（送信）
  sendSlackMessage("📝 *【自動生成された本日の日報】*\n\n" + reportText);
  
  // 6. 必要に応じて、自動生成したダミーデータや日報をDailySummaryシートに追記する処理をここに実装可能
  // recordAutoGeneratedSummary(dailySheet, today, eventsInfo);
}

/**
 * DailySummaryシートから本日の記録があるか確認
 */
function checkTodayRecord(sheet, today) {
  if (!sheet) return false;
  
  const data = sheet.getDataRange().getValues();
  if (data.length <= 1) return false;
  
  const todayYMD = Utilities.formatDate(today, Session.getScriptTimeZone(), "yyyy/MM/dd");
  
  // 既存のシートを上から舐めて、今日の日付の行があれば提出済みと判定
  for (let i = 1; i < data.length; i++) {
    const rowDate = new Date(data[i][0]);
    if (isNaN(rowDate.getTime())) continue;
    
    const rowYMD = Utilities.formatDate(rowDate, Session.getScriptTimeZone(), "yyyy/MM/dd");
    if (todayYMD === rowYMD) {
      return true; // 本日の記録が見つかった
    }
  }
  return false;
}

/**
 * 今日のカレンダー予定を取得
 */
function getTodayCalendarEvents(today) {
  // 当日の0時0分0秒〜23時59分59秒
  const startTime = new Date(today);
  startTime.setHours(0, 0, 0, 0);
  
  const endTime = new Date(today);
  endTime.setHours(23, 59, 59, 999);
  
  let calendar;
  if (DAILY_CONFIG.TARGET_CALENDAR_ID === 'primary') {
    calendar = CalendarApp.getDefaultCalendar(); // デフォルト（自分のカレンダー）
  } else {
    calendar = CalendarApp.getCalendarById(DAILY_CONFIG.TARGET_CALENDAR_ID);
  }
  
  if (!calendar) {
    throw new Error('指定されたカレンダーが見つかりません');
  }
  
  const events = calendar.getEvents(startTime, endTime);
  
  let eventListText = "";
  let totalMinutes = 0;
  
  events.forEach(event => {
    // 終日イベント(祝日など)はスキップする場合
    if (event.isAllDayEvent()) return;
    
    const title = event.getTitle();
    const start = event.getStartTime();
    const end = event.getEndTime();
    
    // イベントの所要時間（分）
    const durationMin = Math.round((end - start) / (1000 * 60));
    totalMinutes += durationMin;
    
    // 時刻のフォーマット
    const startStr = Utilities.formatDate(start, Session.getScriptTimeZone(), "HH:mm");
    const endStr = Utilities.formatDate(end, Session.getScriptTimeZone(), "HH:mm");
                    
    eventListText += `- ${startStr}〜${endStr}: ${title} (${durationMin}分)\n`;
  });
  
  return {
    eventCount: events.length,
    totalMinutes: totalMinutes,
    eventListText: eventListText
  };
}

/**
 * Gemini APIを使って日報を生成
 */
function generateReportWithGemini(eventsInfo, today) {
  if (!DAILY_CONFIG.GEMINI_API_KEY) {
    return '（エラー: Gemini API Keyが設定されていません）';
  }
  
  const dateStr = Utilities.formatDate(today, Session.getScriptTimeZone(), "yyyy年MM月dd日");
  const totalHours = Math.round(eventsInfo.totalMinutes / 60 * 10) / 10;
  
  const prompt = `あなたは優秀なアシスタントです。以下の本日のカレンダー予定データをもとに、日報を自動作成してください。

## 本日の日付
${dateStr}

## カレンダーの予定一覧
稼働時間合計: ${totalHours} 時間
予定件数: ${eventsInfo.eventCount} 件

${eventsInfo.eventListText}

## 作成・出力ルール
- 自動化されたことがわかるように、冒頭に「※この日報はAIによってカレンダー予定から自動生成されました」と一言添えること。
- 予定の一覧から推測される今日の「主な業務内容（箇条書き）」「今日の気付き・所感（推測される内容でOK）」「明日の予定・TODO（もし推測できれば）」の構成で見出しをつけて作成すること。
- 文体は丁寧なビジネス表現（〜でした、〜しました）に統一すること。
- （文字だけでなく、適度に箇条書きを装飾などして見やすくすること）
`;

  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent`;
  
  try {
    const response = UrlFetchApp.fetch(url, {
      method: 'POST',
      contentType: 'application/json',
      headers: { 'x-goog-api-key': DAILY_CONFIG.GEMINI_API_KEY },
      payload: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: { temperature: 0.7, maxOutputTokens: 2048 }
      })
    });
    
    const json = JSON.parse(response.getContentText());
    return json.candidates?.[0]?.content?.parts?.[0]?.text || '日報のテキスト生成に失敗しました（Geminiから空のレスポンス）。';
  } catch (e) {
    Logger.log('Gemini APIエラー: ' + e.message);
    return 'AI日報生成エラー: ' + e.message;
  }
}

/**
 * Slackへ通知を行う
 */
function sendSlackMessage(text) {
  const webhookUrl = DAILY_CONFIG.SLACK_WEBHOOK_URL;
  if (!webhookUrl) {
    Logger.log('Slack Webhook URLが設定されていません。');
    return;
  }
  
  const payload = {
    text: text
  };
  
  const options = {
    method: 'post',
    contentType: 'application/json',
    payload: JSON.stringify(payload)
  };
  
  try {
    UrlFetchApp.fetch(webhookUrl, options);
  } catch(e) {
    Logger.log('Slack通知エラー: ' + e.message);
  }
}

/**
 * ========================================
 * 毎日の自動実行トリガーを設定するための関数
 * （一度だけGASエディタ上で手動実行してください）
 * ========================================
 */
function setupDailyTrigger() {
  // 既存の同名トリガーを削除（重複防止）
  const triggers = ScriptApp.getProjectTriggers();
  triggers.forEach(trigger => {
    if (trigger.getHandlerFunction() === 'checkAndGenerateDailyReport') {
      ScriptApp.deleteTrigger(trigger);
    }
  });
  
  // 毎日指定時間（例: 18時台）に実行するトリガーを作成
  ScriptApp.newTrigger('checkAndGenerateDailyReport')
    .timeBased()
    .everyDays(1)
    .atHour(DAILY_CONFIG.TRIGGER_HOUR)
    .create();
    
  Logger.log(`毎日の日報未提出アラート＆自動生成トリガーを設定しました（毎日 ${DAILY_CONFIG.TRIGGER_HOUR} 時台に実行されます）`);
}
